/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-brand-lime",
    "text-brand-lime",
    "border-brand-lime",
    "text-ink-inverse",
    "text-ink-dim",
    "hover:text-brand-lime",
    "hover:bg-brand-lime",
    "group-hover:text-brand-lime",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "var(--brand-primary)",
          primary: "var(--brand-primary)",
          green: "var(--brand-green)",
          lime: "var(--brand-lime)",
          dark: "var(--brand-dark)",
          deep: "var(--brand-deep)",
          50: "var(--surface-soft)",
          100: "var(--surface-soft)",
          200: "var(--border)",
          300: "var(--brand-green)",
          400: "var(--brand-primary)",
          500: "var(--brand-primary)",
          600: "var(--brand-green)",
          700: "var(--brand-dark)",
          800: "var(--brand-deep)",
          900: "var(--dark-background)",
        },
        ink: {
          DEFAULT: "var(--text-primary)",
          light: "var(--text-secondary)",
          muted: "var(--text-muted)",
          inverse: "var(--color-text-light)",
          dim: "var(--color-text-muted)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          bg: "var(--background)",
          muted: "var(--surface-soft)",
          dark: "var(--dark-surface)",
        },
        line: {
          DEFAULT: "var(--border)",
          strong: "var(--brand-green)",
        },
        background: "var(--background)",
        dark: {
          DEFAULT: "var(--dark-background)",
          surface: "var(--dark-surface)",
          border: "var(--dark-border)",
          muted: "var(--dark-muted)",
        },
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        roboto: ["Manrope", "sans-serif"],
        grotesk: ["Manrope", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "monospace"],
      },
      fontSize: {
        hero: ["var(--so-fs-hero)", { lineHeight: "1.12", letterSpacing: "-0.03em", fontWeight: "800" }],
        h1: ["var(--so-fs-h1)", { lineHeight: "1.15", letterSpacing: "-0.028em", fontWeight: "800" }],
        h2: ["var(--so-fs-h2)", { lineHeight: "1.18", letterSpacing: "-0.025em", fontWeight: "700" }],
        h3: ["var(--so-fs-h3)", { lineHeight: "1.28", letterSpacing: "-0.02em", fontWeight: "700" }],
        h4: ["var(--so-fs-h4)", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
      maxWidth: {
        site: "1200px",
      },
      boxShadow: {
        card: "0 10px 30px rgba(3, 24, 20, 0.06)",
        "card-hover": "0 16px 36px rgba(0, 200, 83, 0.12)",
        btn: "var(--lime-glow)",
      },
      backgroundImage: {
        "gradient-brand": "var(--brand-gradient)",
        "gradient-dark": "var(--hero-gradient)",
        "gradient-hero": "var(--hero-gradient)",
      },
      keyframes: {
        "orbit-spin": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "orbit-spin-reverse": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(-360deg)" } },
        "pulse-soft": { "0%,100%": { transform: "scale(1)" }, "50%": { transform: "scale(1.05)" } },
        "float-y": { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-10px)" } },
        marquee: { from: { transform: "translateX(0)" }, to: { transform: "translateX(-50%)" } },
        "fade-up": { from: { opacity: 0, transform: "translateY(28px)" }, to: { opacity: 1, transform: "translateY(0)" } },
      },
      animation: {
        "orbit-spin": "orbit-spin 26s linear infinite",
        "orbit-spin-reverse": "orbit-spin-reverse 26s linear infinite",
        "orbit-spin-slow": "orbit-spin 18s linear infinite reverse",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "float-y": "float-y 5s ease-in-out infinite",
        marquee: "marquee 28s linear infinite",
      },
      container: {
        center: true,
        padding: { DEFAULT: "var(--so-gutter)", md: "var(--so-gutter)", lg: "var(--so-gutter)" },
      },
    },
  },
  plugins: [],
};
